repos:
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.34.0'
    hooks:
    -   id: eslint
        types_or: [javascript, jsx, ts, tsx]
-   repo: local
    hooks:
    - id: secrettool
      name: secrettool
      language: node
      entry: node 
      pass_filenames: false
      args:
      - -r
      - ts-node/register
      - src/main.ts
      - lint