repos:
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.34.0'
    hooks:
    -   id: eslint
        types_or: [javascript, jsx, ts, tsx]